name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Étape 3 : Installer Azure CLI
    - name: Install Azure CLI
      uses: azure/CLI@v1

    # Étape 4 : Connexion à Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Étape 5 : Déployer sur Azure
    - name: Deploy to Azure Web App
      run: |
        az webapp up --name <your-app-name> --runtime "PYTHON:3.9"
